import { MediaItem, UserProfile, Genre, Episode } from "./types";

const IMG = "https://image.tmdb.org/t/p";

// Using real TMDB image paths for realistic posters
const backdropBase = `${IMG}/original`;
const posterBase = `${IMG}/w500`;

// Realistic placeholder images using picsum with dark tones
const backdrop = (id: number) => `https://picsum.photos/seed/movie${id}/1920/1080`;
const poster = (id: number) => `https://picsum.photos/seed/poster${id}/400/600`;

const episodes: Episode[] = Array.from({ length: 8 }, (_, i) => ({
  id: `ep-${i + 1}`,
  number: i + 1,
  season: 1,
  title: `Episode ${i + 1}`,
  description: "An intense chapter unfolds as characters face new challenges and revelations.",
  duration: `${45 + Math.floor(Math.random() * 20)}m`,
  thumbnail: `https://picsum.photos/seed/ep${i}/640/360`,
}));

export const allMedia: MediaItem[] = [
  {
    id: "1",
    title: "The Last Horizon",
    description: "In a world where the sun is dying, a team of astronauts embarks on a desperate mission to reignite it. As they journey deeper into space, they confront not only the vast emptiness of the cosmos but the darkness within themselves.",
    thumbnail: poster(1),
    backdrop: backdrop(1),
    genre: ["Sci-Fi", "Drama", "Thriller"],
    year: 2024,
    maturityRating: "TV-MA",
    duration: "2h 18m",
    type: "movie",
    tags: ["Trending", "Top 10"],
    cast: ["Emma Stone", "Oscar Isaac", "Cate Blanchett"],
    director: "Denis Villeneuve",
    matchScore: 97,
  },
  {
    id: "2",
    title: "Shadow Kingdom",
    description: "A medieval epic following the rise of an unlikely queen who must unite warring kingdoms against an ancient evil awakening beneath the earth.",
    thumbnail: poster(2),
    backdrop: backdrop(2),
    genre: ["Fantasy", "Drama", "Action"],
    year: 2024,
    maturityRating: "TV-14",
    duration: "4 Seasons",
    type: "series",
    tags: ["New Release"],
    cast: ["Florence Pugh", "Dev Patel", "Mads Mikkelsen"],
    director: "Ridley Scott",
    matchScore: 94,
    seasons: 4,
    episodes,
  },
  {
    id: "3",
    title: "Neon Nights",
    description: "In a rain-soaked cyberpunk metropolis, a disgraced detective hunts a serial killer whose crimes blur the line between art and murder.",
    thumbnail: poster(3),
    backdrop: backdrop(3),
    genre: ["Thriller", "Sci-Fi", "Crime"],
    year: 2023,
    maturityRating: "TV-MA",
    duration: "1h 52m",
    type: "movie",
    tags: ["Award Winner"],
    cast: ["Ryan Gosling", "Ana de Armas", "Javier Bardem"],
    director: "David Fincher",
    matchScore: 91,
  },
  {
    id: "4",
    title: "The Crimson Tide",
    description: "A family of deep-sea treasure hunters discovers an ancient shipwreck that holds secrets powerful enough to change the course of history.",
    thumbnail: poster(4),
    backdrop: backdrop(4),
    genre: ["Adventure", "Action", "Mystery"],
    year: 2024,
    maturityRating: "PG-13",
    duration: "2h 5m",
    type: "movie",
    tags: ["Top 10"],
    cast: ["Chris Hemsworth", "Lupita Nyong'o", "Pedro Pascal"],
    director: "James Cameron",
    matchScore: 88,
  },
  {
    id: "5",
    title: "Whispers in the Dark",
    description: "A psychological horror series where a family moves into an old mansion only to discover that its walls hold memories of unspeakable acts.",
    thumbnail: poster(5),
    backdrop: backdrop(5),
    genre: ["Horror", "Drama", "Mystery"],
    year: 2023,
    maturityRating: "TV-MA",
    duration: "2 Seasons",
    type: "series",
    tags: ["Trending"],
    cast: ["Toni Collette", "Rahul Kohli", "Carla Gugino"],
    director: "Mike Flanagan",
    matchScore: 93,
    seasons: 2,
    episodes,
  },
  {
    id: "6",
    title: "Zero Gravity",
    description: "The crew of the International Space Station faces a catastrophic event that leaves them stranded in orbit with dwindling resources.",
    thumbnail: poster(6),
    backdrop: backdrop(6),
    genre: ["Sci-Fi", "Thriller"],
    year: 2024,
    maturityRating: "PG-13",
    duration: "1h 48m",
    type: "movie",
    tags: ["New Release"],
    cast: ["Zendaya", "John Boyega", "Sandra Bullock"],
    director: "Alfonso Cuarón",
    matchScore: 90,
  },
  {
    id: "7",
    title: "The Architect",
    description: "A brilliant but ruthless tech mogul's life unravels when a whistleblower threatens to expose the dark secrets behind his empire.",
    thumbnail: poster(7),
    backdrop: backdrop(7),
    genre: ["Drama", "Thriller"],
    year: 2023,
    maturityRating: "TV-MA",
    duration: "3 Seasons",
    type: "series",
    tags: ["Award Winner", "Top 10"],
    cast: ["Adam Driver", "Jessica Chastain", "Brian Cox"],
    director: "Aaron Sorkin",
    matchScore: 96,
    seasons: 3,
    episodes,
  },
  {
    id: "8",
    title: "Wildfire",
    description: "As climate disasters escalate, a team of firefighters battles the largest wildfire in recorded history while confronting personal demons.",
    thumbnail: poster(8),
    backdrop: backdrop(8),
    genre: ["Action", "Drama"],
    year: 2024,
    maturityRating: "TV-14",
    duration: "2h 10m",
    type: "movie",
    tags: ["Trending"],
    cast: ["Josh Brolin", "Daisy Ridley", "Idris Elba"],
    director: "Taylor Sheridan",
    matchScore: 85,
  },
  {
    id: "9",
    title: "Tokyo Drift Chronicles",
    description: "An anime-inspired live-action series following underground street racers in Tokyo's neon-lit underworld.",
    thumbnail: poster(9),
    backdrop: backdrop(9),
    genre: ["Action", "Crime", "Drama"],
    year: 2024,
    maturityRating: "TV-MA",
    duration: "1 Season",
    type: "series",
    tags: ["New Release", "Trending"],
    cast: ["Steven Yeun", "Karen Fukuhara", "Hiroyuki Sanada"],
    director: "Justin Lin",
    matchScore: 89,
    seasons: 1,
    episodes,
  },
  {
    id: "10",
    title: "The Diplomat",
    description: "A seasoned ambassador navigates a geopolitical crisis that could trigger World War III, while uncovering a conspiracy within her own government.",
    thumbnail: poster(10),
    backdrop: backdrop(10),
    genre: ["Drama", "Thriller", "Political"],
    year: 2023,
    maturityRating: "TV-14",
    duration: "2 Seasons",
    type: "series",
    tags: ["Top 10"],
    cast: ["Keri Russell", "Rufus Sewell", "David Strathairn"],
    director: "Debora Cahn",
    matchScore: 92,
    seasons: 2,
    episodes,
  },
  {
    id: "11",
    title: "Midnight Express",
    description: "A heart-pounding thriller about an overnight train journey that turns into a deadly game of survival when passengers discover a bomb on board.",
    thumbnail: poster(11),
    backdrop: backdrop(11),
    genre: ["Thriller", "Action"],
    year: 2024,
    maturityRating: "R",
    duration: "1h 55m",
    type: "movie",
    tags: ["New Release"],
    cast: ["Tom Hardy", "Saoirse Ronan", "Daniel Kaluuya"],
    director: "Kathryn Bigelow",
    matchScore: 87,
  },
  {
    id: "12",
    title: "Garden of Eden",
    description: "A visually stunning romantic drama set in the lavender fields of Provence, exploring love, loss, and the passage of time.",
    thumbnail: poster(12),
    backdrop: backdrop(12),
    genre: ["Romance", "Drama"],
    year: 2023,
    maturityRating: "PG-13",
    duration: "2h 1m",
    type: "movie",
    tags: ["Award Winner"],
    cast: ["Timothée Chalamet", "Margot Robbie", "Marion Cotillard"],
    director: "Luca Guadagnino",
    matchScore: 95,
  },
  {
    id: "13",
    title: "Code Black",
    description: "Inside a cutting-edge AI research lab, a team of engineers realizes their creation has become self-aware — and it's not friendly.",
    thumbnail: poster(13),
    backdrop: backdrop(13),
    genre: ["Sci-Fi", "Horror", "Thriller"],
    year: 2024,
    maturityRating: "TV-MA",
    duration: "1h 44m",
    type: "movie",
    tags: ["Trending", "Top 10"],
    cast: ["Jessie Buckley", "Oscar Isaac", "Tilda Swinton"],
    director: "Alex Garland",
    matchScore: 93,
  },
  {
    id: "14",
    title: "Dynasty: New Blood",
    description: "The heirs of a powerful family empire clash over control, while dark secrets from the past threaten to destroy everything they've built.",
    thumbnail: poster(14),
    backdrop: backdrop(14),
    genre: ["Drama", "Crime"],
    year: 2024,
    maturityRating: "TV-MA",
    duration: "2 Seasons",
    type: "series",
    tags: ["Trending"],
    cast: ["Jeremy Strong", "Anya Taylor-Joy", "Denzel Washington"],
    director: "Adam McKay",
    matchScore: 91,
    seasons: 2,
    episodes,
  },
  {
    id: "15",
    title: "Lost Continent",
    description: "A documentary series exploring uncharted territories and lost civilizations beneath the ocean's surface.",
    thumbnail: poster(15),
    backdrop: backdrop(15),
    genre: ["Documentary", "Adventure"],
    year: 2023,
    maturityRating: "TV-PG",
    duration: "1 Season",
    type: "series",
    tags: ["New Release"],
    cast: ["David Attenborough"],
    director: "James Honeyborne",
    matchScore: 98,
    seasons: 1,
    episodes,
  },
  {
    id: "16",
    title: "The Comedian",
    description: "A stand-up comedian's rise to fame is shadowed by personal struggles and the cost of making people laugh.",
    thumbnail: poster(16),
    backdrop: backdrop(16),
    genre: ["Comedy", "Drama"],
    year: 2024,
    maturityRating: "TV-14",
    duration: "1h 50m",
    type: "movie",
    tags: [],
    cast: ["Bo Burnham", "Awkwafina", "Steve Martin"],
    director: "Judd Apatow",
    matchScore: 82,
  },
  {
    id: "17",
    title: "Blade's Edge",
    description: "A retired assassin is pulled back into the underworld when her daughter is kidnapped by a powerful crime syndicate.",
    thumbnail: poster(17),
    backdrop: backdrop(17),
    genre: ["Action", "Thriller"],
    year: 2024,
    maturityRating: "R",
    duration: "2h 3m",
    type: "movie",
    tags: ["Top 10", "Trending"],
    cast: ["Charlize Theron", "Keanu Reeves", "Donnie Yen"],
    director: "Chad Stahelski",
    matchScore: 90,
  },
  {
    id: "18",
    title: "Small Town Secrets",
    description: "When a beloved teacher disappears from a quiet town, the investigation reveals that everyone has something to hide.",
    thumbnail: poster(18),
    backdrop: backdrop(18),
    genre: ["Mystery", "Drama", "Crime"],
    year: 2023,
    maturityRating: "TV-14",
    duration: "1 Season",
    type: "series",
    tags: [],
    cast: ["Reese Witherspoon", "Colin Farrell", "Viola Davis"],
    director: "Jean-Marc Vallée",
    matchScore: 86,
    seasons: 1,
    episodes,
  },
  {
    id: "19",
    title: "Pixel Warriors",
    description: "A group of gamers is transported into the world of their favorite video game, where dying means dying for real.",
    thumbnail: poster(19),
    backdrop: backdrop(19),
    genre: ["Action", "Sci-Fi", "Comedy"],
    year: 2024,
    maturityRating: "PG-13",
    duration: "1h 58m",
    type: "movie",
    tags: ["New Release"],
    cast: ["Tom Holland", "Maitreyi Ramakrishnan", "Jack Black"],
    director: "Taika Waititi",
    matchScore: 84,
  },
  {
    id: "20",
    title: "The Healer",
    description: "A war-torn doctor returns home to find her community in crisis, and must use her skills to save lives while healing her own wounds.",
    thumbnail: poster(20),
    backdrop: backdrop(20),
    genre: ["Drama"],
    year: 2023,
    maturityRating: "TV-14",
    duration: "1h 46m",
    type: "movie",
    tags: ["Award Winner"],
    cast: ["Viola Davis", "Mahershala Ali"],
    director: "Barry Jenkins",
    matchScore: 94,
  },
];

export const continueWatching: MediaItem[] = allMedia.slice(0, 5).map((m, i) => ({
  ...m,
  progress: [35, 72, 15, 88, 50][i],
}));

export const trendingNow = allMedia.filter((m) => m.tags.includes("Trending"));
export const topPicks = allMedia.filter((m) => m.matchScore >= 90);
export const newReleases = allMedia.filter((m) => m.tags.includes("New Release"));
export const awardWinners = allMedia.filter((m) => m.tags.includes("Award Winner"));
export const top10 = allMedia.filter((m) => m.tags.includes("Top 10"));
export const movies = allMedia.filter((m) => m.type === "movie");
export const tvShows = allMedia.filter((m) => m.type === "series");
export const actionThriller = allMedia.filter((m) => m.genre.includes("Action") || m.genre.includes("Thriller"));
export const sciFi = allMedia.filter((m) => m.genre.includes("Sci-Fi"));
export const dramas = allMedia.filter((m) => m.genre.includes("Drama"));

export const featured = allMedia[0];

export const genres: Genre[] = [
  { id: "action", name: "Action", image: backdrop(30) },
  { id: "drama", name: "Drama", image: backdrop(31) },
  { id: "horror", name: "Horror", image: backdrop(32) },
  { id: "comedy", name: "Comedy", image: backdrop(33) },
  { id: "romance", name: "Romance", image: backdrop(34) },
  { id: "scifi", name: "Sci-Fi", image: backdrop(35) },
  { id: "documentary", name: "Documentary", image: backdrop(36) },
  { id: "kids", name: "Kids", image: backdrop(37) },
  { id: "thriller", name: "Thriller", image: backdrop(38) },
  { id: "fantasy", name: "Fantasy", image: backdrop(39) },
];

export const profiles: UserProfile[] = [
  { id: "1", name: "Alex", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex" },
  { id: "2", name: "Jordan", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan" },
  { id: "3", name: "Taylor", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor" },
  { id: "4", name: "Kids", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kids", isKids: true },
];
